SELECT V.NOME, V.CURSODEINTERESSE, I.CURSO, V.ESCOLA, I.INGRESSO
FROM VISITANTES V,INGRESSANTES I
WHERE I.NOME = V.NOME
ORDER BY NOME;



/*
ALUNOS QUE VISITARAM A PRACA E PASSARAM NA UFCG, INFORMANDO O NOME, CURSO QUE PASSOU, CURSO QUE INFORMOU QUANDO PASSOU NA PRAÇA, ESCOLA QUE ESTUDAVA
E PERIODO QUE ENTROU, ORDENADOS POR NOME
SELECT V.NOME, V.CURSODEINTERESSE, I.CURSO, V.ESCOLA, I.INGRESSO
FROM VISITANTES V,INGRESSANTES1 I
WHERE I.NOME = V.NOME
ORDER BY NOME;
*/

/*
ESTUDANTES QUE PASSARAM PARA A UFCG E SÃO DO COLEGIO MOTIVA
SELECT I.CURSO, COUNT(*)
FROM VISITANTES V,INGRESSANTES1 I
WHERE I.NOME = V.NOME AND V.ESCOLA = 'COLEGIO MOTIVA'
GROUP BY I.CURSO;
*/

/*
QUANTIDADE DE ALUNOS QUE PASSARAM POR CURSO
SELECT CURSO,COUNT(*)
FROM CURSOSCORRELACAO
GROUP BY CURSO;
*/

/*




SELECT COUNT(*),CURSODEINTERESSE,CURSO
FROM CURSOSCORRELACAO
WHERE CURSODEINTERESSE = 'SAUDE' OR CURSODEINTERESSE = 'EXATAS' OR CURSODEINTERESSE = 'ALGUMA ENGENHARIA'
GROUP BY CURSODEINTERESSE,CURSO;
*/


SELECT COUNT(*),CURSODEINTERESSE,CURSO
FROM CURSOSCORRELACAO
WHERE CURSODEINTERESSE LIKE '%SAUDE%' OR CURSODEINTERESSE LIKE '%EXATAS%' 
OR CURSODEINTERESSE LIKE '%ENGENHARIA%' OR CURSODEINTERESSE LIKE '%MEDICINA%' OR CURSODEINTERESSE LIKE '%SAUDE%'
GROUP BY CURSODEINTERESSE,CURSO;

SELECT CURSO,CURSODEINTERESSE
FROM CURSOSCORRELACAO;

SELECT V.NOME, V.CURSODEINTERESSE, I.CURSO
FROM VISITANTES V,INGRESSANTES1 I
WHERE I.NOME = V.NOME
ORDER BY NOME;
